### ISSUE TITLE
Pictures are uploaded from iPhone at lower resolution!

### ISSUE THREAD

**Issue by thelwyn** [owncloud/ios#244]
I uploaded quite a few pictures from my iphone, they end up on the server and on my PC at much lower resolution : 852x640!

So you feel like you saved pictures on the cloud and you delete the original one, at full size on phone. Lost many pictures like this :(

It may be related to last iOS8 upgrade that messed up the way Pictures are handled. It seems it made the same problem to Onedrive of Microsoft when synchronizing:

http://answers.microsoft.com/en-us/onedrive/forum/sdoptions-sdcamera/onedrive-for-ios-8-on-iphone-6-plus-only-backs-up/dee80be1-a502-4b3a-9a59-74f796cd3719

http://answers.microsoft.com/en-us/onedrive/forum/sdoptions-sdcamera/onedrive-ios-app-compresses-photos/6b7cf4fc-5325-4659-b861-41210631dc62

They rolled out a new version of their iOS app that I'm using right now, and they fixed the problem.
So should do Owncloud, QUICK. It's a matted of data loss, the most critical problem for a cloud solution huh.

F**\* Apple I guess...

I will get back to using Owncloud app when it's fixed, for now I use Onedrive to save from my iphone and then transfer to my owncloud at full resolution (how ironic!)

**Comment by jdwirtz** [comment]
Has this problem been fixed? I'm using an iPhone 5s, just updated from 8.12 to 8.2.
photos I upload to owncloud are being reduced in size. When I use a USB cable to
copy photos to owncloud they are full size 3264 x2448, but when I upload them from my
iPhone they are 852x640.  Strangly enough when I upload photo from my iPad Mini, it uploads
the full size photo? How can I correct this problem?

**Comment by Azgymb** [comment]
Is this still not fixed? I uploaded the same photo from my iPhone multiple times.
The file transmitted to pc via USB cable
file size: 1.66MB
actual resolution: 3264 x 2448

For the first few uploads the photo was compressed to
file size: 81KB
resolution: 852 x 640

After a few tries it uploaded with 
file size: 1.1MB
resolution: 2448 x 3264
These last to difference might be because of this rotation thing...

I am using an iPhone 6 with iOS 8.3

**Comment by jdwirtz** [comment]
Thanks for looking into this....
But.....
So.....  it going to be hit and miss or upload several times till it might upload the right size?
If so.. that would be very disappointing  way to leave things. 
I tried the same thing, but they all remained the smaller size.  I then went back and uploaded
12 photos, 2 of which came out the full size??   Is this an IOS issue or Owncloud issue???

Jim

**Comment by Azgymb** [comment]
Okay, I did some more testing and these are the results:
1. No apps in background -> take photo -> upload photo via ownCloud app -> photo uploads compressed 
1.1 stop ownCloud app from backgrounder -> view photo in Photos app -> zoom in as far as possible -> upload photo via ownCloud app -> photo uploads correctly
1.2 do not stop ownCloud app from backgrounder -> view photo in Photos app -> zoom in as far as possible -> upload photo via ownCloud app -> photo uploads compressed

2. ownCloud app in background -> take photo -> view photo in Photos app -> zoom in as far as possible -> upload photo via ownCloud app -> photo uploads correctly

So ownCloud must not "see" the photo before you view it in Photos app and zoom in as far as possible in order to upload correctly

**Comment by jdwirtz** [comment]
Ok.. that works on all the pictures I've tried, new or old. 
I didn't have to zoom all the way in, just zoom in some for
it to upload full size.
Wouldn't call this a solution, but a "work around".
Hopefully this is something that can be corrected in a 
future release.

**Comment by javiergonzper** [comment]
@Azgymb thanks for the steps but I can not reproduce the problem following your steps 1, 1.2 o 3
I made a fresh install and try to reproduce all your steps but all the pictures are upload fine (iPhone 5S with iOS 8.3) but all the pictures are upload with the same resolution (3264 × 2448).

Did you do anything more? Maybe there is other thing that you do that you think that it is not important but it is.

@jdwirtz @Azgymb 
Did you remove the App and install it again?

**Comment by jdwirtz** [comment]
I've done nothing more.   I have removed the app and installed it again

with the same results.  I have an iPad Mini, the pictures uploaded from 

it always uploads at the full size.  

 

It does seem that any photo I have taken in the past and zoomed in on

will upload at full size.

 

Jim

**Comment by Azgymb** [comment]
I got some more information:
- reinstalling the app does not fix the issue
- I could not reproduce this issue with: iPhone 5 iOS 8.3; iPad Air 2 iOS 8.1

For everything I mention in this post and my earlier post, the Dropbox app behaves the exact same way.
I normally use the app Files Pro to upload pictures to my dropbox. This upload works fine and has the same effect as viewing the photo in Photos app and zooming in on it.
-> I turned on iCloud Photo Library (Settings -> Photos & Camera) to kind of "force" the iPhone to do the processing work it does when zooming in or uploading photos using the Files Pro app. With this setting turned on at least new photos always upload full size in both, ownCloud and Dropbox app.

As I said I could not reproduce the issue with the mentioned other devices even though they regularly have the iCloud Photo Library turned off.

Tomorrow I might try resetting my phone to factory settings.

**Comment by seraphyn** [comment]
@Azgymb Does resetting the phone help?
Or did you kick it out of the problem and cured the problem with that ;) ?

**Comment by jdwirtz** [comment]
Not for me.

**Comment by Azgymb** [comment]
First of all sorry for not answering this for so long. I did not have the time to reset my phone. Today I installed the iOS public beta 1 and it seems to have fixed the problem - fyi iOS 8.4 did not.

**Comment by jdwirtz** [comment]
Thanks... figured this had been forgotten.

**Comment by michaelstingl** [comment]
fixed in later iOS versions
